Repository CederGroupHub/chgnet, pull requests merged in 2023-06, with the labels that each got.

#37 Drop `jupyter-dash` and update CTK relax viewer
  .pre-commit-config.yaml
  examples/crystaltoolkit_relax_viewer.ipynb
  pyproject.toml
Labels: pkg

#39 API Docs
  .github/workflows/gh-pages.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  chgnet/data/dataset.py
  chgnet/model/dynamics.py
  chgnet/utils/vasp_utils.py
  pyproject.toml
  site/.eslintrc.yml
  site/.gitignore
  site/make_docs.py
  site/package.json
  site/src/app.css
  site/src/app.d.ts
  site/src/app.html
  site/src/routes/+error.svelte
  site/src/routes/+layout.svelte
  site/src/routes/+layout.ts
  site/src/routes/+page.svelte
  site/src/routes/api/+page.svelte
  site/static/chgnet-logo.png
  site/static/chgnet-logo.svg
  site/static/favicon.svg
  site/static/prism-vsc-dark-plus.css
  site/svelte.config.js
  site/tsconfig.json
  site/vite.config.ts
  tests/test_relaxation.py
Labels: documentation

#41 Fix `ValueError: ndarray is not C-contiguous` CI errors
  .github/workflows/test.yml
  README.md
  chgnet/data/dataset.py
  chgnet/graph/converter.py
  chgnet/model/model.py
  chgnet/trainer/trainer.py
  examples/make_graphs.py
  tests/test_converter.py
Labels: testing, fix

#40 2.4x avg speedup on PMG struct to CHGNET graph conversion
  .gitignore
  chgnet/graph/converter.py
  chgnet/graph/cygraph.pyx
  chgnet/graph/fast_converter_libraries/create_graph.c
  chgnet/graph/fast_converter_libraries/uthash.h
  chgnet/model/model.py
  pyproject.toml
  setup.py
  tests/test_converter.py
  tests/test_crystal_graph.py
  tests/test_md.py
  tests/test_model.py
  tests/test_relaxation.py
Labels: enhancement

#42 More descriptive names for single-letter variables
  chgnet/graph/converter.py
  chgnet/graph/cygraph.pyx
  chgnet/model/composition_model.py
  chgnet/model/dynamics.py
  chgnet/model/model.py
  chgnet/trainer/trainer.py
  chgnet/utils/vasp_utils.py
  examples/fine_tuning.ipynb
Labels: housekeeping
