Repository CederGroupHub/chgnet, pull requests merged in 2023-09, with the labels that each got.

#67 1. Fixed units of taut, taup 2. Added missing ttime in NPT
  chgnet/model/dynamics.py
  tests/test_md.py
Labels: fix

#69 Fix `StructureData` inconsistent labels length error
  chgnet/data/dataset.py
  tests/test_dataset.py
Labels: fix, data

#68 Implement lattice transform to upper-triangular matrix for ASE Nose-Hoover thermostat
  chgnet/model/dynamics.py
  examples/mp-1175469-Li9Co7O16.cif
  tests/test_md.py
Labels: enhancement, needs testing, md

#70 Make repo citable
  .pre-commit-config.yaml
  README.md
  citation.cff
Labels: documentation, pkg

#71 Publish pre-compiled wheels for all platforms to PyPI in release CI
  .github/workflows/lint.yml
  .github/workflows/test.yml
  setup.py
Labels: pkg, CI

#72 Drop Python 3.8 support
  .github/workflows/test.yml
  README.md
  chgnet/data/dataset.py
  chgnet/model/basis.py
  chgnet/model/composition_model.py
  chgnet/model/functions.py
  chgnet/model/model.py
  examples/basics.ipynb
  examples/crystaltoolkit_relax_viewer.ipynb
  pyproject.toml
Labels: pkg, breaking
