Repository CederGroupHub/chgnet, pull requests merged in 2024-09, with the labels that each got.

#201 Fix missing `create_graph.c` in source distribution
  pyproject.toml
Labels: pkg, fix

#184 `ruff` fixes
  .github/workflows/test.yml
  chgnet/graph/converter.py
  chgnet/graph/graph.py
  chgnet/model/composition_model.py
  chgnet/model/dynamics.py
  chgnet/model/model.py
  chgnet/trainer/trainer.py
  chgnet/utils/vasp_utils.py
  pyproject.toml
  setup.py
  tests/test_converter.py
  tests/test_crystal_graph.py
  tests/test_encoders.py
  tests/test_relaxation.py
  tests/test_trainer.py
  tests/test_vasp_utils.py
Labels: linting

#203 Remove reverse readline, test again NP1 and recover NumPy 1 dependency support
  .github/workflows/test.yml
  chgnet/utils/vasp_utils.py
  pyproject.toml
Labels: pkg, fix

#204 Drop Python 3.9 support
  .github/workflows/release.yml
  .pre-commit-config.yaml
  README.md
  chgnet/graph/converter.py
  chgnet/graph/graph.py
  chgnet/model/composition_model.py
  chgnet/model/dynamics.py
  chgnet/model/functions.py
  chgnet/model/model.py
  chgnet/trainer/trainer.py
  chgnet/utils/vasp_utils.py
  examples/crystaltoolkit_relax_viewer.ipynb
  pyproject.toml
Labels: pkg, compatibility
